# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RunScreen1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Start_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Start_Button.setGeometry(QtCore.QRect(260, 200, 251, 61))
        self.Start_Button.setObjectName("Start_Button")
        self.Instruction_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Instruction_Button.setGeometry(QtCore.QRect(260, 290, 251, 61))
        self.Instruction_Button.setObjectName("Instruction_Button")
        self.Quit_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Quit_Button.setGeometry(QtCore.QRect(260, 380, 251, 61))
        self.Quit_Button.setObjectName("Quit_Button")
        self.Title_label = QtWidgets.QLabel(self.centralwidget)
        self.Title_label.setGeometry(QtCore.QRect(250, 70, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Title_label.setFont(font)
        self.Title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_label.setObjectName("Title_label")
        self.Name_Label = QtWidgets.QLabel(self.centralwidget)
        self.Name_Label.setGeometry(QtCore.QRect(10, 531, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.Name_Label.setFont(font)
        self.Name_Label.setObjectName("Name_Label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Restuarant Deciding App (V1.1)"))
        self.Start_Button.setText(_translate("MainWindow", "Start"))
        self.Instruction_Button.setText(_translate("MainWindow", "How to use"))
        self.Quit_Button.setText(_translate("MainWindow", "Quit"))
        self.Title_label.setText(_translate("MainWindow", "Welcome to Restuarant Decider!"))
        self.Name_Label.setText(_translate("MainWindow", "By Kai Obertelli (Student No: 33612821)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
