# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RunScreen2Test.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(189, 29, 591, 531))
        self.stackedWidget.setStyleSheet("Background-Color:grey")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.label = QtWidgets.QLabel(self.Home)
        self.label.setGeometry(QtCore.QRect(150, 40, 211, 101))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.Home)
        self.Red = QtWidgets.QWidget()
        self.Red.setStyleSheet("background-color: Red")
        self.Red.setObjectName("Red")
        self.stackedWidget.addWidget(self.Red)
        self.Yellow = QtWidgets.QWidget()
        self.Yellow.setStyleSheet("background-color: Yellow")
        self.Yellow.setObjectName("Yellow")
        self.stackedWidget.addWidget(self.Yellow)
        self.Blue = QtWidgets.QWidget()
        self.Blue.setStyleSheet("background-color: Blue")
        self.Blue.setObjectName("Blue")
        self.stackedWidget.addWidget(self.Blue)
        self.BButton = QtWidgets.QPushButton(self.centralwidget)
        self.BButton.setGeometry(QtCore.QRect(40, 40, 75, 23))
        self.BButton.setObjectName("BButton")
        self.RButton = QtWidgets.QPushButton(self.centralwidget)
        self.RButton.setGeometry(QtCore.QRect(40, 110, 75, 23))
        self.RButton.setObjectName("RButton")
        self.YButton = QtWidgets.QPushButton(self.centralwidget)
        self.YButton.setGeometry(QtCore.QRect(40, 180, 75, 23))
        self.YButton.setObjectName("YButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Restuarant Deciding App (V1.1)"))
        self.label.setText(_translate("MainWindow", "How to use..."))
        self.BButton.setText(_translate("MainWindow", "Blue"))
        self.RButton.setText(_translate("MainWindow", "Red"))
        self.YButton.setText(_translate("MainWindow", "Yellow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
