# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RunScreen3Test.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(129, 69, 651, 521))
        self.stackedWidget.setStyleSheet("Background-Color:grey")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.label = QtWidgets.QLabel(self.Home)
        self.label.setGeometry(QtCore.QRect(60, 40, 141, 21))
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.Home)
        self.textBrowser.setGeometry(QtCore.QRect(50, 80, 571, 361))
        self.textBrowser.setObjectName("textBrowser")
        self.stackedWidget.addWidget(self.Home)
        self.Red = QtWidgets.QWidget()
        self.Red.setStyleSheet("background-color: Red")
        self.Red.setObjectName("Red")
        self.LocLabel = QtWidgets.QLabel(self.Red)
        self.LocLabel.setGeometry(QtCore.QRect(90, 60, 47, 13))
        self.LocLabel.setObjectName("LocLabel")
        self.DistLabel = QtWidgets.QLabel(self.Red)
        self.DistLabel.setGeometry(QtCore.QRect(90, 150, 47, 13))
        self.DistLabel.setObjectName("DistLabel")
        self.PRLabel = QtWidgets.QLabel(self.Red)
        self.PRLabel.setGeometry(QtCore.QRect(90, 250, 71, 21))
        self.PRLabel.setObjectName("PRLabel")
        self.pushButton = QtWidgets.QPushButton(self.Red)
        self.pushButton.setGeometry(QtCore.QRect(240, 350, 171, 61))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.Red)
        self.Yellow = QtWidgets.QWidget()
        self.Yellow.setStyleSheet("background-color: Yellow")
        self.Yellow.setObjectName("Yellow")
        self.stackedWidget.addWidget(self.Yellow)
        self.Blue = QtWidgets.QWidget()
        self.Blue.setStyleSheet("background-color: Blue")
        self.Blue.setObjectName("Blue")
        self.stackedWidget.addWidget(self.Blue)
        self.BButton = QtWidgets.QPushButton(self.centralwidget)
        self.BButton.setGeometry(QtCore.QRect(10, 300, 111, 41))
        self.BButton.setObjectName("BButton")
        self.RButton = QtWidgets.QPushButton(self.centralwidget)
        self.RButton.setGeometry(QtCore.QRect(10, 140, 111, 41))
        self.RButton.setObjectName("RButton")
        self.YButton = QtWidgets.QPushButton(self.centralwidget)
        self.YButton.setGeometry(QtCore.QRect(10, 220, 111, 41))
        self.YButton.setObjectName("YButton")
        self.MainLabel = QtWidgets.QLabel(self.centralwidget)
        self.MainLabel.setGeometry(QtCore.QRect(130, 10, 651, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.MainLabel.setFont(font)
        self.MainLabel.setObjectName("MainLabel")
        self.InstructionButton = QtWidgets.QPushButton(self.centralwidget)
        self.InstructionButton.setGeometry(QtCore.QRect(20, 70, 91, 31))
        self.InstructionButton.setObjectName("InstructionButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Restuarant Deciding App (V1.1)"))
        self.label.setText(_translate("MainWindow", "How to use..."))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">Description on how to use the app will be here</span></p></body></html>"))
        self.LocLabel.setText(_translate("MainWindow", "Location"))
        self.DistLabel.setText(_translate("MainWindow", "Distance"))
        self.PRLabel.setText(_translate("MainWindow", "Price Range"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.BButton.setText(_translate("MainWindow", "3) Roulette"))
        self.RButton.setText(_translate("MainWindow", "1) Search"))
        self.YButton.setText(_translate("MainWindow", "2) Sort"))
        self.MainLabel.setText(_translate("MainWindow", "Welcome to Restuarant Deciding App V1.1!"))
        self.InstructionButton.setText(_translate("MainWindow", "How to Use"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
